site_name: Family Music System

nav:
  - Home: index.md
  - Visão do produto e projeto:
      - Visão geral do produto: visao-produto-projeto/visao-produto.md
      - Visão geral do projeto: visao-produto-projeto/visao-projeto.md
      - Processo de desenvolvimento de software: visao-produto-projeto/processo-de-desenvolvimento-de-software.md
      
  - Backlog do Produto: backlog_produto/backlog_produto.md
  - Design:
      - Arquitetura do produto: design/arquitetura_do_produto.md
      - Padrões de interface: design/padroes_de_interface.md
  - CI Test:
      - Documentação do CI: ci-test/ci-test.md
  - Entregas:
      - Unidade 1: entregas\unidade-1.md
      - Unidade 2: entregas\unidade-2.md
      - Unidade 3: entregas\unidade-3.md
      - Unidade 4: entregas\unidade-4.md
  - Sprints: sprint/sprints.md
  - Lições Aprendidas: visao-produto-projeto/licoes-aprendidas.md
repo_url: https://github.com/mdsreq-fga-unb/2023.1-FamilyMusicSystem
repo_name: FamilyMusicSystem
theme:
  name: material
  language: pt
  favicon: images/logo-color.png
  logo: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.edit
    - content.action.view
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: yellow
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: amber
      toggle:
        icon: material/weather-sunny
        name: Modo claro
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
